version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.13-management
#    container_name: 'rabbitmq'
    ports:
#      - 5672:5672
      - 15674:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - my-network
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: Lavka
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5434:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - my-network
    command: /bin/sh -c "mkdir -p ./pg_data && docker-entrypoint.sh postgres"
  app_lavka:
    build: ../Proect_Lavka
    ports:
      - "8082:8083"
    depends_on:
      - db
      - rabbitmq
    networks:
      - my-network
  app:
    build: .
    ports:
      - "8080:8081"
    depends_on:
      - db
      - rabbitmq
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
volumes:
  pg_data:
    driver: local