version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: 'rabbitmq'
    ports:
#      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - my-network
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: Lavka
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
#    ports:
#      - "5434:5432"
    networks:
      - my-network
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
      - rabbitmq
    networks:
      - my-network
  app_lavka:
    build: ../Proect_Lavka
    ports:
      - "8083:8083"
    depends_on:
      - db
      - rabbitmq
    networks:
      - my-network
networks:
  my-network:
    driver: bridge