version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: Lavka
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
#    ports:
#      - "5434:5432"
    networks:
      - my-network
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - my-network
networks:
  my-network:
    driver: bridge